RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260919_074103293/surge/direct.conf,DIRECT
RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260919_074103293/surge/claude-ai.conf,ClaudeAI
RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260919_074103293/surge/none-cn-ai.conf,国外AI
RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260919_074103293/surge/media-sns.conf,媒体社交
RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260919_074103293/surge/google.conf,谷歌服务
RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260919_074103293/surge/tiktok.conf,国际抖音
RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260919_074103293/surge/devcode-tools.conf,开发依赖
RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260919_074103293/surge/global-cdn.conf,全球加速
RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260919_074103293/surge/direct-ip.conf,DIRECT
RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260919_074103293/surge/claude-ai-ip.conf,ClaudeAI
RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260919_074103293/surge/none-cn-ai-ip.conf,国外AI
RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260919_074103293/surge/media-sns-ip.conf,媒体社交
RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260919_074103293/surge/global-cdn-ip.conf,全球加速
