RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260922_202930312/surge/none-cn-ai_process.conf,国际AI
RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260922_202930312/surge/youtube_domain.conf,proxy
RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260922_202930312/surge/none-cn-ai_domain.conf,国际AI
RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260922_202930312/surge/google_domain.conf,国际AI
RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260922_202930312/surge/media-sns_domain.conf,proxy
RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260922_202930312/surge/tiktok_domain.conf,国际抖音
RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260922_202930312/surge/devcode-tools_domain.conf,proxy
RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260922_202930312/surge/global-cdn_domain.conf,proxy
RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260922_202930312/surge/china_ip.conf,DIRECT,no-resolve
RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260922_202930312/surge/none-cn-ai_ip.conf,国际AI,no-resolve
RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260922_202930312/surge/media-sns_ip.conf,proxy,no-resolve
RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260922_202930312/surge/global-cdn_ip.conf,proxy,no-resolve
