RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260922_172847403/surge/none-cn-ai_process.conf,国际AI
RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260922_172847403/surge/youtube_domain.conf,proxy
RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260922_172847403/surge/none-cn-ai_domain.conf,国际AI
RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260922_172847403/surge/google_domain.conf,国际AI
RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260922_172847403/surge/media-sns_domain.conf,proxy
RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260922_172847403/surge/tiktok_domain.conf,国际抖音
RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260922_172847403/surge/devcode-tools_domain.conf,proxy
RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260922_172847403/surge/global-cdn_domain.conf,proxy
RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260922_172847403/surge/china_ip.conf,DIRECT
RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260922_172847403/surge/none-cn-ai_ip.conf,国际AI
RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260922_172847403/surge/media-sns_ip.conf,proxy
RULE-SET,https://fastly.jsdelivr.net/gh/AnyGong/proxy-tools-rules@v20260922_172847403/surge/global-cdn_ip.conf,proxy
