PROCESS-NAME,UURemote
PROCESS-NAME,nUURemoteDaemon
PROCESS-NAME,nUURemoteService
PROCESS-NAME,WeChat
PROCESS-NAME,WeChatAppEx
PROCESS-NAME,WeChatHelper
PROCESS-NAME,微信 Helper
PROCESS-NAME,QQ
PROCESS-NAME,QQ Helper
PROCESS-NAME,QQMini
PROCESS-NAME,QQGuild
PROCESS-NAME,QQDoc
PROCESS-NAME,Desktop Pet
PROCESS-NAME,Doubao
PROCESS-NAME,Doubao Browser
PROCESS-NAME,Doubao Browser Helper
PROCESS-NAME,Thunder
